name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.0

    - name: Set up Node.js
      uses: actions/setup-node@v14  # En yüksek desteklenen sürüm
      with:
        node-version: '14'

    - name: Install Dependencies and Build
      run: |
        cd frontend-app
        npm install
        npm run build

    - name: Install Dependencies and Test
      run: |
        cd backend-app
        npm install
        npm test
